name: Zonova_Mist
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  flutter_dotenv: ^6.0.0
  universal_html: ^2.2.4
  photo_view: ^0.15.0
  file_picker: ^10.3.6
  just_audio: ^0.9.36

  # Core packages
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # Networking
  http: ^1.2.1
  dio: ^5.4.3+1
  http_parser: ^4.0.2
  cloudinary_public: 0.23.1

  # State Management
  flutter_riverpod: ^2.5.1

  # UI / UX
  flutter_slidable: ^3.0.1
  carousel_slider: ^5.1.1
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  photo_view: ^0.15.0
  url_launcher: ^6.1.6
  universal_html: ^2.2.4
  flutter_dotenv: ^6.0.0
  image_picker: ^1.1.2

  # Forms
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2

  # Secure Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  # Optional: Adaptive icon for Android (recommended)
  adaptive_icon_background: "#ffffff"  # White background
  adaptive_icon_foreground: "assets/icons/logo.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  generate: true
